
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.salonbooking: DEBUG
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
