server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: salon-service

  datasource:
    url: jdbc:postgresql://${SALON_DB_HOST:localhost}:${SALON_DB_PORT:5433}/${SALON_DB_NAME:salondb}
    username: ${SALON_DB_USER:salon}
    password: ${SALON_DB_PASSWORD:salon}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
