rootProject.name = 'salon-booking-system'

include ':api'
include ':util'

include ':microservices:salon-service'
include ':microservices:auth-service'

// Ostali moduli se dodaju u narednim delovima projekta (deo po deo, commit po commit):
// include ':microservices:catalog-service'
// include ':microservices:staff-service'
// include ':microservices:booking-service'
// include ':microservices:review-service'
// include ':microservices:notification-service'
// include ':spring-cloud:eureka-server'
// include ':spring-cloud:config-server'
// include ':spring-cloud:gateway'
