server:
  port: 8084
  error:
    include-message: always

spring:
  application:
    name: staff-service

  datasource:
    url: jdbc:postgresql://${STAFF_DB_HOST:localhost}:${STAFF_DB_PORT:5436}/${STAFF_DB_NAME:staffdb}
    username: ${STAFF_DB_USER:staff}
    password: ${STAFF_DB_PASSWORD:staff}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
